IF "%TARGET%"=="" SET TARGET=TRICORE
IF "%DERIVATE%"=="" SET DERIVATE=TC23XL
IF "%SUBDERIVATE%"=="" SET SUBDERIVATE=M4_SUBDERIVATE
IF "%TOOLCHAIN%"=="" SET TOOLCHAIN=tasking
IF "%TOOLPATH_COMPILER%"=="" SET TOOLPATH_COMPILER=C:\Compiler\TASKING\TriCore_v5.0r2\ctc
PUSHD %CD%
cd ..
IF "%PROJECT_ROOT%"=="" SET PROJECT_ROOT=%CD%
cd ..
cd ..
IF "%WORKSPACE_BASE%"=="" SET WORKSPACE_BASE=%CD%
POPD
IF "%M_CAN_PROTOCOL_TYPE%"=="PROTOCOL_TYPE_CANFD" (
    SET TRESOS_BASE=%WORKSPACE_BASE%\SourceCode\PLUGIN\AUTOSAR\ASR403_TC23X_AC_V201
) ELSE (
    SET TRESOS_BASE=%WORKSPACE_BASE%\SourceCode\PLUGIN\AUTOSAR\ASR403_TC23X_V501
    )
)
SET TRESOS_PLUGIN=%TRESOS_BASE%\plugins
